---
- name: Install required packages and setup virtual environment
  hosts: webservers
  become: yes

  tasks:
    - name: Install required packages (Ubuntu)
      apt:
        name:
          - python3
          - python3-pip
          - git
          - python3-venv
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install required packages (CentOS)
      yum:
        name:
          - python3
          - python3-pip
          - git
        state: present
      when: ansible_distribution == "CentOS"

    - name: Set up a virtual environment (Ubuntu)
      become: yes
      command: "python3 -m venv /home/ubuntu/Flask-App/flask_env"
      when: ansible_distribution == "Ubuntu"

    - name: Set up a virtual environment (CentOS)
      become: yes
      command: "python3 -m venv /home/ubuntu/Flask-App/flask_env"
      when: ansible_distribution == "CentOS"

    - name: Install Flask library
      ansible.builtin.pip:
        name: Flask
        executable: /home/ubuntu/Flask-App/flask_env/bin/pip3
        state: present

    - name: Install Gunicorn
      ansible.builtin.pip:
        name: gunicorn
        executable: /home/ubuntu/Flask-App/flask_env/bin/pip3
        state: present

    - name: Install Nginx (Ubuntu)
      apt:
        name: nginx
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Nginx (CentOS)
      yum:
        name: nginx
        state: present
      when: ansible_distribution == "CentOS"
...
